{
 "title": "Redis Cluster",
 "description": "Prometheus dashboard for Redis servers",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(redis_up{project=~\"dk\"},cluster)"
   },
   {
    "name": "sections",
    "label": "区组",
    "query": "label_values(redis_up{cluster=~\"$cluster\"}, sections)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(redis_up{cluster=~\"$cluster\", sections=~\"$sections\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{instance=~\"$node\"}  / redis_config_maxmemory{instance=~\"$node\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$node\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$node\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$node\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "slaves",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_connected_slaves{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "connections used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": " redis_connected_clients{instance=~\"$node\"} / redis_config_maxclients{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$node\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_config_maxmemory{instance=~\"$node\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$node\"}) - sum (redis_db_keys_expiring{instance=~\"$node\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$node\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$node\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_command_call_duration_seconds_count{instance=~\"$node\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$node\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$node\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  }
 ]
}